version: "3"
services:
  node:
    build: node/.
    environment: 
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
    volumes:
      - ./node:/node
    working_dir: /node
    command: ["npm", "start"]
    ports:
      - "3000:3000"